import cheekuImg from "../images/temp/cheekusvg.svg";

export const productData = {
    "Todays Deal": [
        {
            id: 1,
            imageUrl: cheekuImg,
            title: "Wireless Bluetooth Headphones",
            oldPrice: "$50.00",
            newPrice: "$40.00",
        },
        {
            id: 2,
            imageUrl: cheekuImg,
            title: "4K Ultra HD Smart TV",
            oldPrice: "$600.00",
            newPrice: "$499.00",
        },
        {
            id: 3,
            imageUrl: cheekuImg,
            title: "Electric Toothbrush",
            oldPrice: "$90.00",
            newPrice: "$70.00",
        },
        {
            id: 4,
            imageUrl: cheekuImg,
            title: "Smart Fitness Tracker",
            oldPrice: "$120.00",
            newPrice: "$100.00",
        },
        {
            id: 5,
            imageUrl: cheekuImg,
            title: "Portable Power Bank",
            oldPrice: "$40.00",
            newPrice: "$30.00",
        },
        {
            id: 6,
            imageUrl: cheekuImg,
            title: "Smartwatch",
            oldPrice: "$150.00",
            newPrice: "$120.00",
        },
        {
            id: 7,
            imageUrl: cheekuImg,
            title: "Gaming Console",
            oldPrice: "$300.00",
            newPrice: "$250.00",
        },
        {
            id: 8,
            imageUrl: cheekuImg,
            title: "Wireless Keyboard and Mouse",
            oldPrice: "$50.00",
            newPrice: "$40.00",
        },
    ],
    "Top Offer": [
        {
            id: 9,
            imageUrl: cheekuImg,
            title: "Noise Cancelling Headphones",
            oldPrice: "$150.00",
            newPrice: "$130.00",
        },
        {
            id: 10,
            imageUrl: cheekuImg,
            title: "Touchscreen Laptop",
            oldPrice: "$900.00",
            newPrice: "$799.00",
        },
        {
            id: 11,
            imageUrl: cheekuImg,
            title: "Gaming Laptop",
            oldPrice: "$1200.00",
            newPrice: "$999.00",
        },
        {
            id: 12,
            imageUrl: cheekuImg,
            title: "Tablet",
            oldPrice: "$300.00",
            newPrice: "$250.00",
        },
    ],
    "Top Rated": [
        {
            id: 13,
            imageUrl: cheekuImg,
            title: "Portable Bluetooth Speaker",
            oldPrice: "$60.00",
            newPrice: "$50.00",
        },
        {
            id: 14,
            imageUrl: cheekuImg,
            title: "Smartphone Case",
            oldPrice: "$25.00",
            newPrice: "$20.00",
        },
        {
            id: 15,
            imageUrl: cheekuImg,
            title: "LED Desk Lamp",
            oldPrice: "$35.00",
            newPrice: "$28.00",
        },
        {
            id: 16,
            imageUrl: cheekuImg,
            title: "Wireless Charger",
            oldPrice: "$30.00",
            newPrice: "$25.00",
        },
        {
            id: 17,
            imageUrl: cheekuImg,
            title: "Smart Home Hub",
            oldPrice: "$100.00",
            newPrice: "$80.00",
        },
    ],
    Fruits: [
        {
            id: 18,
            imageUrl: cheekuImg,
            title: "Fresh Apples",
            oldPrice: "$5.00",
            newPrice: "$4.50",
        },
        {
            id: 19,
            imageUrl: cheekuImg,
            title: "Ripe Bananas",
            oldPrice: "$3.00",
            newPrice: "$2.50",
        },
        {
            id: 20,
            imageUrl: cheekuImg,
            title: "Juicy Oranges",
            oldPrice: "$6.00",
            newPrice: "$5.50",
        },
        // Add more products here
        {
            id: 21,
            imageUrl: cheekuImg,
            title: "Strawberries",
            oldPrice: "$8.00",
            newPrice: "$7.00",
        },
        {
            id: 22,
            imageUrl: cheekuImg,
            title: "Blueberries",
            oldPrice: "$10.00",
            newPrice: "$9.00",
        },
    ],
    Vegetables: [
        {
            id: 23,
            imageUrl: cheekuImg,
            title: "Fresh Carrots",
            oldPrice: "$2.00",
            newPrice: "$1.80",
        },
        {
            id: 24,
            imageUrl: cheekuImg,
            title: "Organic Lettuce",
            oldPrice: "$3.00",
            newPrice: "$2.50",
        },
        {
            id: 25,
            imageUrl: cheekuImg,
            title: "Fresh Spinach",
            oldPrice: "$4.00",
            newPrice: "$3.50",
        },
        {
            id: 26,
            imageUrl: cheekuImg,
            title: "Broccoli",
            oldPrice: "$3.00",
            newPrice: "$2.50",
        },
        {
            id: 27,
            imageUrl: cheekuImg,
            title: "Cauliflower",
            oldPrice: "$4.00",
            newPrice: "$3.50",
        },
    ],
    Snacks: [
        {
            id: 28,
            imageUrl: cheekuImg,
            title: "Salted Potato Chips",
            oldPrice: "$2.50",
            newPrice: "$2.00",
        },
        {
            id: 29,
            imageUrl: cheekuImg,
            title: "Chocolate Chip Cookies",
            oldPrice: "$3.00",
            newPrice: "$2.50",
        },
        {
            id: 30,
            imageUrl: cheekuImg,
            title: "Gummy Candy",
            oldPrice: "$1.50",
            newPrice: "$1.00",
        },
        {
            id: 31,
            imageUrl: cheekuImg,
            title: "Popcorn",
            oldPrice: "$2.00",
            newPrice: "$1.50",
        },
        {
            id: 32,
            imageUrl: cheekuImg,
            title: "Trail Mix",
            oldPrice: "$3.50",
            newPrice: "$3.00",
        },
    ],
};
